name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run checks
      run: |
        # Проверка на отсутствие файлов с расширениями css, js в директории src
        if [ -n "$(find ./src -name '*.css' -o -name '*.js')" ]; then
          echo "Warning: CSS or JS files found in ./src directory"
        fi

        # Другие проверки могут быть добавлены здесь

    - name: Build
      run: |
        # Команды для сборки проекта

    - name: Deploy
      run: |
        # Команды для деплоя проекта
